### ISSUE TITLE
Status not working anymore

### ISSUE THREAD

**Issue by nate331** [numerai/numerai-cli#51]
Since very recently I receive the following error when running `numerai node -m <my_node_name> status -n 200`:

``` 
Task status: STOPPED. Checking for log events...
Traceback (most recent call last):
  File "/home/test/daf_env/bin/numerai", line 8, in <module>
    sys.exit(main())
  File "/home/test/daf_env/lib/python3.7/site-packages/numerai/cli/__init__.py", line 40, in main
    numerai()
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/test/daf_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/test/daf_env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/test/daf_env/lib/python3.7/site-packages/numerai/cli/node/test.py", line 337, in status
    monitor(node, load_or_init_nodes(node), verbose, num_lines, log_type, follow_tail)
  File "/home/test/daf_env/lib/python3.7/site-packages/numerai/cli/node/test.py", line 140, in monitor
    monitor_aws(node, config, num_lines, log_type, follow_tail, verbose)
  File "/home/test/daf_env/lib/python3.7/site-packages/numerai/cli/node/test.py", line 209, in monitor_aws
    next_token, num_events = print_logs(logs_client, family, name, limit=num_lines)
  File "/home/test/daf_env/lib/python3.7/site-packages/numerai/cli/node/test.py", line 304, in print_logs
    **kwargs
  File "/home/test/daf_env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/test/daf_env/lib/python3.7/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/test/daf_env/lib/python3.7/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/test/daf_env/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter logStreamName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```
Running this for nodes which ran last week works fine. But running this for nodes which ran today is resulting in this error.

**Comment by wasserth** [comment]
It seems to be working again now.
