### ISSUE TITLE
numerai uninstall does not work

### ISSUE THREAD

**Issue by r-matsuzaka** [numerai/numerai-cli#63]
Hi,
I run `numerai uninstall`, then I got the error.

```
ryo@ryo:~$ numerai uninstall
DANGER WILL ROBINSON, This will:
    - Destroy all nodes in the cloud
    - Remove all docker images on your computer
    - Delete the .numerai configuration directory on your computer
    - Uninstall the numerai-cli python package
    - Leave Python and Docker installed on your computer
    
Are you absolutely sure you want to uninstall? [y/N]: y
deregistering all webhooks...
destroying cloud resources...
Running: docker run -e "AWS_ACCESS_KEY_ID=...UAE5N"  -e "AWS_SECRET_ACCESS_KEY=...QvF4n" --rm -it -v /home/ryo/.numerai:/opt/plan -w /opt/plan hashicorp/terraform:0.14.3 destroy -auto-approve -var="node_config_file=nodes.json"
/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/subprocess.py:966: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
 

 Destroy complete! Resources: 0 destroyed.

cleaning up docker images...
Deleted Networks:
docker_default
gpu-docker-notebook_default

Deleted Volumes:
10bc77bc46dbfc3975264bcb4863ef15d305b50cd55a4ed1efaa382b980600e4
a05d51461871e612d054a5d5a3a7a204e98c3124eabe04b1f671003e764d1e80
79f56510f026bd5e188a6714a36bd97fd63ebd57ebd0958803572de5cee4b4d0
9a63c76812f951d159ef6cd81a19642756d712aff4e48233d6381ed1bc10e938
d2326928af1928c5b2ca9c3a99ea74df074749aecda068e888ce8ed29fcf2690
daee3efa1be5c6f73e19832136d547cf18d57786cf7f445fdce9425385e685c9
30b509fb3049f9ab80a4e60b0371b132934b14db9785ff9830c5c88f92317f23
524cfd2906e18799ce7e71efa81a0fa1c5ba7e331c0959dd05fa429226ef68bf
74e49d40eb57e4e38fb388462622f5685560b1f6b112a4ef902abdcddf64a793
0b7c2e9988db6921bf09f636af7366b9501b24f5d32c74d87f287032ab7e9b8c
7b8c00f14e8bb682783a5e152bdce612b7c41eaa4f785fd11946c9057b41ff3d
pack-cache-library_web-service-gin_latest-a7654d0a63af.launch
52d23f0284bf8d1a514ecd69b400f0cdf547d109d3d6bc8db211c9f7db5d40f8
pack-cache-library_web-service-gin_latest-a7654d0a63af.build
6a63e169fe8010ef6dba78fd3909219be88f2187e8cc2dc4cc46af37f07e01b5
6b23578b4ffebc087db74ab373a0e9a3416021e5f905d810d9eb32ff714618bb
0dd8349bde6a6a6d2df97c042a7c6301422e6a29e57ab39d4bf333e176d9981c
46f263cc613a9025fe7a01205dd76628d409c05148228a3e881745c7f6473255
5dd30e27066b9d280967b90ad451719a738ed0ab544365dc2648575d0bbdeef3
00ebb0ad4ed3d92727871023b0e0b8298e1e4b293f8cc3f1795ad2a7d9b82b10
beb4ec3d9644ba0eaac52fc64e590bdcd8dcfdf8a49beec7082c1a8ae2af0dde
a4cd982b2a822993896a645695db80af0bc08b2ec26763b1853f86c9c82bcc2c
4ee52052757c5afd32885f74ffbba1ffed09fbe5a2923486e398fe037138ab84
69f75e557bef0f229c7672f47d2e6f2550c2b4f856b2d2d0dc7aac0f804248a6
08e9d6ae9700653b1b88dfd039cafc123b9ba78416347e045b570bc38029a1c4
45184b4341cccd643b84c660b4c0535f0b5d4ed818f4b689f9d435b3b43f1e07
a07643929ff4872fb0027fcb4db82fb3a54c063dcff977633f82d289c5e87d65
a1418ab62fdc2c7daba010c89502147b3df75b844f0bee317382c1735fe068d5
d7e590edac27f0144cc282434e1f9956b259d836d482bb81d27329e4d5988a3a
261539bff3ac8f40342d638d96ece9446d07fb82cf45a03f4a47307f500d923b
04efbf9013867487b607d9485fe9b58886d73f2e6e254a518ea92690ed9590a5
1eded0857567127fb4232301423317f9cfa552f5351e2c2d61d802388e6e9d0d
3ce8bd9d574317b844d15f363c73443d1160f85c3f9e3d35523b95ec1d2db9e9
45932ed5e1fab73d3223d4ddb688e7654ab1af68d6895da3ce9d78efc0d80cb5
e7c2b1f5c124d280bb6370c5abe3575175341487d20a55f74c6fd83edfdb186a
0953ad999f3c9e9ff17448135cbec61b3c1af76a658032945ad9f0949b1428c3
1019c2693d0655d9cbf385cc9bf5f5c2e5752f5dbdf14e83d9010fcac3ea6d59
3e663eedddff1d8a9efe662f87be5e76dc9ac3632803254b71422312c3e7ee0b
8c8dbf455341cae178e2e314810c00431674f7b8c48cfa01fe50610d1094b277
cb0f6c52bcc3ac4a996e1bb710cab93aa970e6ba25d62a6e7a107ea3959ae180
4057cab773b592cde5dd32f5368b141c0af60af4023b2f5c4fe729089e68fd69
4b410da334b1d465f328726f869e584bb56ef59f272350bc7fcbe99abfbbe3f0
6cec8a3be77826cd6adb3df67de54677f0c9184fec20e71f0c15bd681a7fdb68
42790d8dc6626d404d4c50ee2e1601479894bd6b37b096926de6222d3dfe6957
e0a95f2e875b09127126bd1a08ef65ab580ade862b916e9bf8404dbc5473a898
4a5516874ca2938d30aa0a989564cd76982363c60653c918995448bd8a0f4eb9
474ace900a50519c95328125cb8714c8a1bc45a00218afbd9ca07790130cc931
da06d2b39fc5c4a79873472213f99a23d92aa7d19d4a0fa22be3ba37b288633a
2beb3fe82c8d8f5d78228252c568825891a1e6c99169713dd85995b001008f08
3c422a6773306ecab6e8307f6321bd1a8feb9c710722276585d9bd90c3e9ee96
41285b1655cc5300d01485a8c9205229e840a43627805a5e414318ef4501af97
4cd7de361402174f49fa39e2248b2799ccdc90262c5395bf7ae74649901e3903
0def9eae1cdfc2144bdf02b021660f50d9a195edead0549e35c92185e846ff29
3731aa6592500376bd045cc5e7cef1d01a2cfada864788a27ff5fdfe5c56e5b2

Deleted Images:
untagged: gcr.io/numerai-train-380407/numerai_train:v1
untagged: gcr.io/numerai-train-380407/numerai_train@sha256:520f4da6ac0ab7bc379f9d354d21123e5437c375da28215a094e5edf7fc3cc08
deleted: sha256:a7ef8343766f118cb983e90ee2c8267622349aa48f1bbaefeea9701339d7dc8e
deleted: sha256:130e695f4225384fce0b51ec5614f2bf5a158061e5a49917717a855a0986d091
deleted: sha256:85c707a9f8451fe6019817acb8b7caed26de986b0645cb4c7156b7b3d2a698c2
deleted: sha256:9a526cac5215f695ce26a93f4864c91973aaccc31a38143d963feffaa1a554c6
deleted: sha256:4323ae4d4d03b736cd66f2a92e62f97685fe16cc8cdc4eb94b707ef28160e544
deleted: sha256:9aa1ad08a0ea84172736ea582af89963a74050ac62dfc21a650c1433901bbd7b
deleted: sha256:16a6ebee40f59d7d8735fe394fe8d25d6f389724de0aecbb7674fed09e7619ec
deleted: sha256:3e57c9cae462970103ae2da0da7b160b3b0fba0699554c9ec75969b12bcc95e5
deleted: sha256:8ca065b63be97b1b7cbf24b93a1ce019911a6881e48b9bfb134083b55fff3fb1
deleted: sha256:3f05c1353bb290cdb01652f20900bb6dea4e24221489e024ba8a563dd1bc09e6
untagged: ubuntu:jammy
untagged: ubuntu@sha256:67211c14fa74f070d27cc59d69a7fa9aeff8e28ea118ef3babc295a0428a6d21
untagged: numerai_train:latest
untagged: gcr.io/numerai-train-380407/numerai_train:v3
untagged: gcr.io/numerai-train-380407/numerai_train@sha256:cb0de436514e79050e3925ed2feb1197e0412363370d3c8a0b1b5897e79f80d5
deleted: sha256:ea968b6742125c4b7005d3e2279bf5dad6efd7aa405e4759451ed96fc8705d89
deleted: sha256:48ab31c979701303207ef1f8ab75f766466de96979f383d016a20376294a19ba
deleted: sha256:335baee244da9f3b5a864ecbba68018bb4b644fc300196a4352c542c88debec6
deleted: sha256:8a07333f267e4e0653389a538d7a92149b9508f3f12d641fb5f620ac14d3513c
deleted: sha256:086170f38aa0f1d35511bbf6ce6dc630528d1bb8defd05e6693252c3b9b63f35
deleted: sha256:0d3eff770490996571e73bedaa63210ee2a95240f6ddbbda9fa8d968802a9d1e
deleted: sha256:f6487120c7fa56d9f73d4ba1dda9a9ccc3c2463e0f3dedf8b2c8e680bd405e7e
deleted: sha256:d7948b12c7e704c1d820cada9738694eeb4872d5829fef3f3f65db17f0426b10
deleted: sha256:b69f97d268553511e565337093d51a0068d90d92e44f3d2ab46537af472b5e78
deleted: sha256:ce2d78b8d754c817e411908b4f2d92b892a4b8997da8e6bfbfbe8eee15cbdfb7
untagged: python:3.9
untagged: python@sha256:940ea29f268668b00305e22a93e3cbd0f3b05a221716a134f55a3ad8f88bc09f
untagged: hashicorp/terraform:0.14.3
untagged: hashicorp/terraform@sha256:7b1e232f564132b949b812ee138249b5398bedf3c6fab42b468d4ec8acf5343c
deleted: sha256:7de55dfbda43eafac5d7789dd3c2ded5764c217e8369f92b366ff295044e9276
deleted: sha256:147d3b3f755035feeebcc54d4ef3c93ca0d41197ac509860eec8e467840c1be8
deleted: sha256:55fb9c3878040da6312f5ecd202ce610fafeb89f3d269e4b6ce34b55cdcf2242
deleted: sha256:777b2c648970480f50f5b4d0af8f9a8ea798eea43dbcf40ce4a8c7118736bdcf
untagged: gcr.io/numerai-train-380407/numerai_train:v2
untagged: gcr.io/numerai-train-380407/numerai_train@sha256:1564fa2afef36abdd38904ce73391409327847df954f24b839082104889bfc70
deleted: sha256:e97a20cc47eaada853e59a39c904d3dee4fc5f39dfa730915d9ef03d44397cc7
deleted: sha256:3dbe6007b2e8934078f9ce7474ce2c23543883954cf63eeb829c0c15bea298b2
deleted: sha256:99d9b0dafdd98583a52f5180357f1dd95f4e91b432b00a32852c002ede4bdee0
deleted: sha256:b8d0534aa3d362e8eb7dc83a7d0e0010af5315178007af3b199919efb04d8d28
deleted: sha256:c402edaeaa33ee084127fd9b6a7a2f568536cb21e50b07bdbdffb0b570b0f332
deleted: sha256:851f698c87b38e20c479f18b284017693be6c882de56355de6e141a4613a04dc
deleted: sha256:902754042245241fa7c1adcb1cd34cf13cfb8527b26539d4d19d9ffa7b011b44
deleted: sha256:5ecf3235946edc2d19bd829c7546c31b49c8a28036fe0ee866dc8bc5b368b8a0
deleted: sha256:0caff0a39cf7df050bb39a324e1bcb6318ce439023e572e32b61ba14ca6b8660
deleted: sha256:b11ba5738de3deb26027002290f5f71d97b3178c51d07001d9cce5385995bca1
deleted: sha256:d791e6e698ef87fd321de46d5beab643648f40bb4298b337d2c9996d2258c629
deleted: sha256:64c8acaaaac788800f5e5456b1aea74979fcbac8b0505c356d84b0322ee208cf
deleted: sha256:b88df9a29e9398c2697e30ac7541862976decb2c12e561dba262d8c0f8ee5e31
deleted: sha256:e648f1d832e634df1b3c34cc01e629741a927f575f9cdf1c35e9366d5dcfbd43
deleted: sha256:a5478c151d8dfd77ad7f4f679457e6187d6b2e2c436d166f666e354877e22e07
deleted: sha256:b266848c946f5d31878314cc7e184ca50ec021efe8ecd52fc982b3d19d813ac0
deleted: sha256:a3fa7ba8502ceaa7673e435124dcf651beee3a5ceb83799c13b3818adbca3ec7
deleted: sha256:b1ec25030aae0f79541be9ac91dbf4fe09ecfcfbef8129ee65e05a08c3443087
deleted: sha256:e80fe057e7e9acff454ad1ccaad1fbd1ad7fe7aa73d866b1ac59e190767c0d41
deleted: sha256:3138fc71aa0528043a2808bbd24099bc29c383e71fe1f6a6b2da3a710f769fdc
deleted: sha256:1bc919fd58897e983633a34c36169216e488bbd3fca7d5e66d97a4784a458873
deleted: sha256:07fe31ff6a48afe38377916596011168209b75de1c7cdd9b341b9284960d49c1
deleted: sha256:2f829da080d33183f0979d06c79ab25da4c6ce7b829a5fa403d150f4761ea66d
deleted: sha256:f6e396e3e7d60242d36af2a3283895cd17006d3ba8fe695fbd8ea5b07fd71fb4
deleted: sha256:3b4744e4ff4e9d974371f9fd55078cae47a191ee6e351519ec24faa5bd72f2fc
deleted: sha256:22f3ef74b51fc7fd3e7c416bb870199b01c2d346148b8ad78b00bfcd7b1b1ba5
deleted: sha256:58300f0e0634b327f5bb48e7a47bae37969dc880dde07831a2da890e5235d0d9
deleted: sha256:76956b37da842da7d2eeed4fc635860274d86b2a0fda154a18567c3fde55b196
deleted: sha256:71a3a8881bc00dc2d77e4df2d988a27bd2ac95b7aaf0373ac2b6b860daf4051e
deleted: sha256:40bce771f6ab0b779848547c8514ec05cb781f510d4e9ed726176aaaf1ce64b7
deleted: sha256:599c04c412b5682c98d7ddc3fc993040524fe7ab56c1a9800fde7d220b710458
deleted: sha256:ba42c72410690ca2af7cadb4d72131c367bfeea3975280d5b6606a559baad703
deleted: sha256:2ad1877da5d54b552999190887b64c8fb4063173f4a68fe437f941f3ac00c52a
deleted: sha256:941d331a4eac90ceb2d8665cb7b6321a7fa5c8a55f758566c98889d6dd80f3ef
deleted: sha256:943d83cb96f180db4373565d16120caa739b724e8f990d8abb5f5249390ebc68
deleted: sha256:f688568e9cb27220d7f2d2e11eaf4a084a10dd190e06b35c157c90793d69795e
deleted: sha256:9a22b8a3e57e7e738aa963b25b86cd55212d0f819a5f5dea81536b7b5127aab3
deleted: sha256:2088989cc3b46f766c41f9bae3136d2a4b4bbc8d8482068d9fd60da557c37a3d
deleted: sha256:be1ffa5f6a501817ae5be8e6ded675227be842406a707e1045906095e20bff17
deleted: sha256:ce7ed6e9efdeb0441fd7f2c4fb6fdc679df09abadcb6f9107152f06fb826e6e8
deleted: sha256:4f503b0081a85d5f8afabf428184cdcd735d76b4b0486e5f42eb7cef46c8b5ec
deleted: sha256:56602c9d18b6abeab4603207db075129c760036fe2273d4bb0fcf39866e36089
deleted: sha256:08d22c0ceb150ddeb2237c5fa3129c0183f3cc6f5eeb2e7aa4016da3ad02140a
deleted: sha256:b93c1bd012ab8fda60f5b4f5906bf244586e0e3292d84571d3abb56472248466
untagged: 995261702419.dkr.ecr.us-east-1.amazonaws.com/numerai-dragon5:latest
deleted: sha256:e287c7d7157caffc328dc3d77cddbf9112c19fccea9e20ca3aee9e7aa4566e9a
deleted: sha256:313dff9db019960b2c12cb850fbe33c55145bd6abb5896dae9d2c7d127ab093c
deleted: sha256:e3279f6fd849a71a9fe6b3ce57210787ee3261f1485692f2466719690744beb8
deleted: sha256:a6070a90c45e63359c2133b36f952e06d31140ece8898e5c0a6d650fade95b41
deleted: sha256:0c36e5292d27e89ea4eae62bf155a66e36ed45e788b45bedcc822b215ce89aa7
deleted: sha256:96e78432f3664843471d359d7899d85d10d1fc5e25d128945b4d2943016154f3
deleted: sha256:41f284dc415892a3961d063d7b32139e3c723d228ccc890821c4c2a94a80bddf
deleted: sha256:a2d367e5a7a24ce3007e3e21bd6148b38f8bce83f579359c0b927b30599dc7cf
deleted: sha256:5a14c44adfcd2941a9fe7333adf2b31628b7da75c355cfe7ef851a7ba08df6e4
deleted: sha256:d5217cef7805ad6a6c02e1c874ec8e9cf845f260049d8de3f5775802d1c6f5d7
deleted: sha256:87b0eec74d3681e24ca34e7f3c7bbccec01e1e271ea069462920ff2f974dfc8b
deleted: sha256:c41accdc0f3e1132ff3313d24d19d4fdffe45397ff2055231fcce39888985b5f
deleted: sha256:4477cf86390e1ac0cefe94d97810b0fa7ac0b26b7a924be3f8fc891fc14ed72d
deleted: sha256:bc8108acd5598ae8cf3a9911737e7fddb543d8d1c7b43aaee141d13ce2065e47
deleted: sha256:064fe3d9e183e40347445d94579646e486bf116852d3c9714bf1038bb8ca6674
deleted: sha256:5407c5455ab9da6157328d0e6c7bdd114b84cdb13f811bf1fee4c34142802be0
deleted: sha256:340d10ece5d2b9cbd458cdb3f230e3ee4be6d6dce28ec002a1996c9b5b3c9aea
deleted: sha256:bc59a87ad71a6afd87105c7f342c98d8f11f9ba4072fbaab0109edb70b180b4f
deleted: sha256:6715c0df67bb838c76f360374a3bb89464e9ca9623306806c854e94d40669d40
deleted: sha256:1a8a6e8f79ade2ad59c565d1a648b43b84ff5fc3c8dbeb54923c07f80ede6ffc
deleted: sha256:5854296b7b5272f9fca16aeefada5d8889589e7482111527233eb0c5cf49887e
deleted: sha256:4bd5dbb78e6e1753498d1ae81fb5f03d6d44860d7c3446c1710c95a0b3a57c4d
deleted: sha256:094992bf0b7ec3c683a5e1e6bc6646c1bd7fe2a5ed8fae69caa2bc377772ee2c
deleted: sha256:b56126d075560162bcc9b81650a524aa43b19e598b13b6f5102cd80cc774579c
deleted: sha256:cf2e8433dbf248a87d49abe6aa4368bb100969be2267db02015aa9c38d7225ed

Deleted build cache objects:
stc7i4049gv7k7cojlh3alsub
ze509ndyhx24fl09yzfsqnytp
keoxu5iwjq3bekoe3ynh9kpeu
u9z1yzrftf0cddk8rsyqoq8ld
wn0t3gpbt49xvka9mr7j6s7w6
la5q88ohc2989faak0tscbsgx
gthzyh3h8g9jukerma9kew1t2
goazrjwjrlaz7le6hafjaoa5d
u6pjic4dk2a9tqjfi67cart0k
jeas2y5s3g0haz76dv2o2dfu5
g5cegnrepwchwxqu1o0hsaj28
44jogowk77pxtb47qpk3gde83
ucwg48nv3p0xwacebtvdvuu66
o9rbr26i5nygnll5r43azq3fe
sjg186g7r533jiiimzm2y196s
snzqdwpq0wkiea5lmss3ycp2f
cq3fclyj999tr4xd4ofdmw8lq
vfhh8fty3bg6t84gvptkcmtii
7iaxo5c1bc8fhul2nv5rb1orf
ejt2bqp9q4glrewntohvkqi5j
kbps1495sybmbprag9qzdgp6q
r9sng73uhycgf6mwz9hn45h3l
ppcrkep1n1rwz6kyy9gmbob0s
5u3wgtrq2a4ol567bv98izswx
zrvplnw2n4nu1d17a2u0behhy
j0dfyss4gvftlt2c32ermer69
ym1vhda9f2dnxcmsftyg56vjc
5odaqhe6q5s4mwp6yzbfuiuqn
j9b3wemdngevjvp81uzy5wejm
rnlvhaun6z9v9kuoq41qlfvfn
mpxbj4hozxyrs9c9rad5prcip
puu73dis5tw9f3a4exkth3xf0
lqf01a89gr62vq7ox85sreoei
v2pwigd8jg2badixcv6ipgq8u
w6wqy5sdk51hx35fs6b7vfhik
xrakj4v1fajif3za1ivla85vb
he7rvv6q6ikf167135lszs3p4
2as0ch7b6tchrtaux6hx0c8x9
fxnvg8aob6gsr7j9q4j4hx31z
76itepcl6gv2vf7h6ju51c31f
ha6cr1mcyy4sa4thmmvpgbqvs
vdrshtvcbv4j9bgya5zvx8pan
3w8ovupwltexou0lnj70qzqjz
tuf6anf6fos47dhnyam7cdaz4
sjmca4u9fslyklmd5vrcivicu
zpak1w6m0fm54cowaw6tuxfbe
rlb97jxwacly8pnmfrxmd9rtf
uor2e98zj7u16as5262nrxz4r
j418x879udep9f2aonxrgxn32
23frdapwklh94kj56gzk2yvzf
ezzm9m6gu5knaytbco2bbgws1
o9ug0tfw4qqrz1oxc086bfemx
7i5khbs4cusmsndfzr3txqwlt
6fpw3apqkd5o0r8fpa1azy5ku
jkrxk0qkoveqyqd013p1m0gn3
ibcnv4rcwzw4jrz709x0z2qx8
19rgbf5ekqxqtzc4b0adamg39
rvcyw1iklaiummg8kkpr3o9n5
ecsqmc45kpqzf0ni3fh4xzr6m
dedx76xs1959l8zbgutpdwqzi
gvlncl3rv65tiw8co5hwwpkz2
ktm4n54yewkpldtkw8fj31yuj
ocqi7cl8xpvh0d44tkaq877fu
dvwhuys2fjqkr4zz5wlpxtbak

Total reclaimed space: 222.7GB
Traceback (most recent call last):
  File "/home/ryo/.local/lib/python3.10/site-packages/numerai/cli/uninstall.py", line 58, in uninstall
    shutil.rmtree(CONFIG_PATH)
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 724, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 4 more times]
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 680, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/ryo/.pyenv/versions/3.10.8/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'terraform-provider-aws_v4.58.0_x5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryo/.local/bin/numerai", line 8, in <module>
    sys.exit(main())
  File "/home/ryo/.local/lib/python3.10/site-packages/numerai/cli/__init__.py", line 40, in main
    numerai()
  File "/home/ryo/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ryo/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ryo/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ryo/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ryo/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ryo/.local/lib/python3.10/site-packages/numerai/cli/uninstall.py", line 60, in uninstall
    root_cause('', str(e))
  File "/home/ryo/.local/lib/python3.10/site-packages/numerai/cli/util/debug.py", line 39, in root_cause
    all = f'{std_out.decode("utf-8") }\n{err_msg.decode("utf-8") }'
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
ryo@ryo:~$
```

**Comment by r-matsuzaka** [comment]
But AWS resources seems to be deleted. Is this error no problem?
