### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.identity'

### ISSUE THREAD

**Issue by ashkan-leo** [numerai/numerai-cli#86]
When following [instructions](https://github.com/numerai/numerai-cli?tab=readme-ov-file#getting-started) to set this up for GCP, I get the exception `ModuleNotFoundError: No module named 'azure.identity'` when I reach the step to run `numerai setup --provider gcp `

Full stack trace:
```
Traceback (most recent call last):
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/bin/numerai", line 5, in <module>
    from numerai import main
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/lib/python3.11/site-packages/numerai/__init__.py", line 1, in <module>
    from numerai.cli import main
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/lib/python3.11/site-packages/numerai/cli/__init__.py", line 4, in <module>
    from numerai.cli import (
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/lib/python3.11/site-packages/numerai/cli/destroy_all.py", line 6, in <module>
    from numerai.cli.util.docker import terraform
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/lib/python3.11/site-packages/numerai/cli/util/docker.py", line 12, in <module>
    from numerai.cli.util.keys import (
  File "/Users/ashkan/Library/Caches/pypoetry/virtualenvs/numer-ai-EQGVgUYP-py3.11/lib/python3.11/site-packages/numerai/cli/util/keys.py", line 10, in <module>
    from azure.identity import ClientSecretCredential  # DefaultAzureCredential
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'azure.identity'
```

**Comment by ashkan-leo** [comment]
This may be related to https://github.com/Azure/azure-cli/issues/22192

**Comment by ashkan-leo** [comment]
Is it a requirement to umbrella install and troubleshoot all the cloud SDKs (Azure, AWS, GCP)?
